export const GET_ERRORS = "GET_ERRORS";
export const GET_CLIENTES = "GET_CLIENTES";
export const GET_CLIENTE = "GET_CLIENTE";
export const DELETE_CLIENTE = "DELETE_CLIENTE";
export const POST_EMPRESTIMO = "POST_EMPRESTIMO";
